language: ruby

rvm:
  - 2.7.1

addons:
  chrome: stable

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

gemfile:
  - examples/rails_app/Gemfile

env:
  global:
    - CI="travis"

before_install:
  - nvm install node
  - node -v
  - npm i -g yarn

script:
  - bin/rails_tests

notifications:
  email: false
