language: ruby

bundler_args: --without development

rvm:
  - 2.7.1

addons:
  chrome: stable

gemfile:
  - Gemfile

env:
  global:
    - CI="travis"
    - CC_TEST_REPORTER_ID=995c46f3c70a74590a7affa80e4341b22d7a86035d1e29d7d18a136f2226de1c

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false
