[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version" # uncomment if using pnpm to skip npm install

[build]
  ignore = "./scripts/docs-check.sh"
  publish = "docs/.vitepress/dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run docs:build"
