# frozen_string_literal: true

# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.
ENV['RACK_ENV'] ||= 'test'

require 'cucumber/rails'

# Make test helpers available in feature files.
require 'capybara_test_helpers/cucumber'
require Rails.root.join('test_helpers/base_test_helper')

ActionController::Base.allow_rescue = false

DatabaseCleaner.strategy = :truncation
Cucumber::Rails::Database.javascript_strategy = :truncation

# Require all hooks.
Dir[Rails.root.join('features/support/hooks/**/*.rb')].sort.each { |f| require f }
Dir[Rails.root.join('spec/system/support/**/*.rb')].sort.each { |f| require f }
