env:
  RUBY_VERSION: 2.7

name: rails

on: [push, pull_request]

defaults:
  run:
    working-directory: ./examples/rails_app

jobs:
  build:
    name: RSpec & Cucumber
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run RSpecs
        run: bin/rspec
      - name: Run Cucumber
        run: bin/cucumber
      - name: Upload coverage results to GitHub
        uses: actions/upload-artifact@main
        with:
          name: coverage-report
          path: coverage
