env:
  RUBY_VERSION: 3.1

name: rails

on: [push]

defaults:
  run:
    working-directory: examples/rails_app

jobs:
  build:
    name: Cucumber & RSpec
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ env.RUBY_VERSION }}
          working-directory: examples/rails_app

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.1.6
          run_install: |
            - cwd: examples/rails_app
            - recursive: false

      - name: Precompile Assets
        run: bin/bundle exec rake assets:precompile
      - name: Run Cucumber
        run: bin/bundle exec cucumber
      - name: Run RSpec
        run: bin/bundle exec rspec
