env:
  RUBY_VERSION: 2.7

name: cucumber

on: [push, pull_request]

defaults:
  run:
    working-directory: examples/rails_app

jobs:
  build:
    name: Cucumber
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ env.RUBY_VERSION }}
          working-directory: examples/rails_app

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: |
          yarn install --ignore-engines --frozen-lockfile
      - name: Precompile Assets
        run: bin/bundle exec rake webpacker:compile
      - name: Run Cucumber
        run: bin/bundle exec cucumber
