env:
  RUBY_VERSION: 2.7

name: build

on: [push]

jobs:
  build:
    name: RSpec & Rubocop
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Update Chrome
        run: |
          sudo apt-get update
          sudo apt-get --only-upgrade install google-chrome-stable
          google-chrome --version
      - uses: nanasess/setup-chromedriver@master
      - name: ChromeDriver Version
        run: chromedriver --version
      - name: Setup Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Run tests
        run: bin/rspec
      - name: Lint Ruby code
        run: bin/rubocop lib
      - name: Upload code coverage to Code Climate
        run: |
          export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
          ./cc-test-reporter after-build -r ${{secrets.CC_TEST_REPORTER_ID}}
      - name: Upload coverage results to GitHub
        uses: actions/upload-artifact@main
        with:
          name: coverage-report
          path: coverage
